[package]
name = "RedisServer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concat-string = "1.0.1"

[dev-dependencies]
parameterized = "1.1.0"